// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TH.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Th {

  /// <summary>Holder for reflection information generated from TH.proto</summary>
  public static partial class THReflection {

    #region Descriptor
    /// <summary>File descriptor for TH.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static THReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CghUSC5wcm90bxICdGgidQoJR3JvdXBJbmZvEhEKCWdyb3VwX2xlbhgBIAEo",
            "BRIPCgdvYnNfbGVuGAIgASgFEhQKCG9ic19saXN0GAMgAygCQgIQARIXCgty",
            "ZXdhcmRfbGlzdBgEIAMoAkICEAESFQoJZG9uZV9saXN0GAUgAygFQgIQASIj",
            "CghHcm91cEFjdBIXCgthY3Rpb25fbGlzdBgBIAMoBUICEAEiBwoFRW1wdHky",
            "WwoMQ29tbXVuaWNhdG9yEiQKB1NlbmRBY3QSDC50aC5Hcm91cEFjdBoJLnRo",
            "LkVtcHR5IgASJQoHR2V0SW5mbxIJLnRoLkVtcHR5Gg0udGguR3JvdXBJbmZv",
            "IgBCFwoFaW8udGhCB1RIUHJvdG9QAaICAlRIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Th.GroupInfo), global::Th.GroupInfo.Parser, new[]{ "GroupLen", "ObsLen", "ObsList", "RewardList", "DoneList" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Th.GroupAct), global::Th.GroupAct.Parser, new[]{ "ActionList" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Th.Empty), global::Th.Empty.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GroupInfo : pb::IMessage<GroupInfo> {
    private static readonly pb::MessageParser<GroupInfo> _parser = new pb::MessageParser<GroupInfo>(() => new GroupInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GroupInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Th.THReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupInfo(GroupInfo other) : this() {
      groupLen_ = other.groupLen_;
      obsLen_ = other.obsLen_;
      obsList_ = other.obsList_.Clone();
      rewardList_ = other.rewardList_.Clone();
      doneList_ = other.doneList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupInfo Clone() {
      return new GroupInfo(this);
    }

    /// <summary>Field number for the "group_len" field.</summary>
    public const int GroupLenFieldNumber = 1;
    private int groupLen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GroupLen {
      get { return groupLen_; }
      set {
        groupLen_ = value;
      }
    }

    /// <summary>Field number for the "obs_len" field.</summary>
    public const int ObsLenFieldNumber = 2;
    private int obsLen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ObsLen {
      get { return obsLen_; }
      set {
        obsLen_ = value;
      }
    }

    /// <summary>Field number for the "obs_list" field.</summary>
    public const int ObsListFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_obsList_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> obsList_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> ObsList {
      get { return obsList_; }
    }

    /// <summary>Field number for the "reward_list" field.</summary>
    public const int RewardListFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_rewardList_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> rewardList_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> RewardList {
      get { return rewardList_; }
    }

    /// <summary>Field number for the "done_list" field.</summary>
    public const int DoneListFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_doneList_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> doneList_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> DoneList {
      get { return doneList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GroupInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GroupInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GroupLen != other.GroupLen) return false;
      if (ObsLen != other.ObsLen) return false;
      if(!obsList_.Equals(other.obsList_)) return false;
      if(!rewardList_.Equals(other.rewardList_)) return false;
      if(!doneList_.Equals(other.doneList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GroupLen != 0) hash ^= GroupLen.GetHashCode();
      if (ObsLen != 0) hash ^= ObsLen.GetHashCode();
      hash ^= obsList_.GetHashCode();
      hash ^= rewardList_.GetHashCode();
      hash ^= doneList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GroupLen != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GroupLen);
      }
      if (ObsLen != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ObsLen);
      }
      obsList_.WriteTo(output, _repeated_obsList_codec);
      rewardList_.WriteTo(output, _repeated_rewardList_codec);
      doneList_.WriteTo(output, _repeated_doneList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GroupLen != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GroupLen);
      }
      if (ObsLen != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ObsLen);
      }
      size += obsList_.CalculateSize(_repeated_obsList_codec);
      size += rewardList_.CalculateSize(_repeated_rewardList_codec);
      size += doneList_.CalculateSize(_repeated_doneList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GroupInfo other) {
      if (other == null) {
        return;
      }
      if (other.GroupLen != 0) {
        GroupLen = other.GroupLen;
      }
      if (other.ObsLen != 0) {
        ObsLen = other.ObsLen;
      }
      obsList_.Add(other.obsList_);
      rewardList_.Add(other.rewardList_);
      doneList_.Add(other.doneList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GroupLen = input.ReadInt32();
            break;
          }
          case 16: {
            ObsLen = input.ReadInt32();
            break;
          }
          case 26:
          case 29: {
            obsList_.AddEntriesFrom(input, _repeated_obsList_codec);
            break;
          }
          case 34:
          case 37: {
            rewardList_.AddEntriesFrom(input, _repeated_rewardList_codec);
            break;
          }
          case 42:
          case 40: {
            doneList_.AddEntriesFrom(input, _repeated_doneList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GroupAct : pb::IMessage<GroupAct> {
    private static readonly pb::MessageParser<GroupAct> _parser = new pb::MessageParser<GroupAct>(() => new GroupAct());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GroupAct> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Th.THReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupAct() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupAct(GroupAct other) : this() {
      actionList_ = other.actionList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupAct Clone() {
      return new GroupAct(this);
    }

    /// <summary>Field number for the "action_list" field.</summary>
    public const int ActionListFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_actionList_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> actionList_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> ActionList {
      get { return actionList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GroupAct);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GroupAct other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!actionList_.Equals(other.actionList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= actionList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      actionList_.WriteTo(output, _repeated_actionList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += actionList_.CalculateSize(_repeated_actionList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GroupAct other) {
      if (other == null) {
        return;
      }
      actionList_.Add(other.actionList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            actionList_.AddEntriesFrom(input, _repeated_actionList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Empty : pb::IMessage<Empty> {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Th.THReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty(Empty other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
